version: "3.9"
services:
  dotnet:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - ./service-reapprovisionnement/:/app/
    ports:
      - 6500:5200
      - 5001:5001
    tty: true
    stdin_open: true
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - MONGO_URL=mongodb://user:pswd@mongo-reappro:27017/
      - MONGO_DATABASE=reappro
      - RABBIT_HOST=rabbit

  discovery:
    image: consul:1.15
    ports:
      - 8500:8500

  serveur-conf:
    image: ghcr.io/laurich-app/serveur-conf:0.0.3
    ports:
      - 8888:8888
    environment:
      - CONSUL_HOST=discovery

  postgres:
    image: postgres:12.17
    environment:
      - POSTGRES_DB=service-utilisateur
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pswd

  service-utilisateur:
    image: ghcr.io/laurich-app/service-utilisateur:1.1.0
    ports:
      - 8081:8080
    environment:
      - URL_CONFIG_SERVEUR=http://serveur-conf:8888
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - PRIVATE_KEY=app_pkcs8.prv
      - PUBLIC_KEY=app.pub
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/service-utilisateur
      - POSTGRES_USER=user
      - POSTGRES_PSWD=pswd
    depends_on:
      - serveur-conf
      - discovery

  mongo-reappro:
    image: mongo:7.0.5
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pswd

  mongo-express:
    image: mongo-express:1.0.2-20
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pswd
      ME_CONFIG_MONGODB_URL: mongodb://user:pswd@mongo-reappro:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo-reappro
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true

  postgres-catalogue:
    image: postgres:12.17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=service-catalogue
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pswd

  rabbit:
    image: rabbitmq:3.12.13-management
    ports:
      - 15672:15672
      - 5672:5672
