version: "3.9"
services:
  dotnet:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - ./service-reapprovisionnement/:/app/
    ports:
      - 6500:5000
      - 5001:5001
      - 5230:5230
    tty: true
    stdin_open: true
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500

  discovery:
    image: consul:1.15
    ports:
      - 8500:8500

  serveur-conf:
    image: ghcr.io/laurich-app/serveur-conf:0.0.3
    ports:
      - 8888:8888

  postgres:
    image: postgres:12.17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=service-utilisateur
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pswd

  service-utilisateur:
    image: ghcr.io/laurich-app/service-utilisateur:1.1.0
    ports:
      - 8081:8080
    environment:
      - URL_CONFIG_SERVEUR=http://serveur-conf:8888
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - PRIVATE_KEY=app_pkcs8.prv
      - PUBLIC_KEY=app.pub
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/service-utilisateur
      - POSTGRES_USER=user
      - POSTGRES_PSWD=pswd
    depends_on:
      - serveur-conf
      - discovery
